# Generated by Django 5.0.7 on 2024-07-19 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='UserHistory',
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'City'},
        ),
        migrations.AlterModelOptions(
            name='userhistory',
            options={'verbose_name_plural': 'History'},
        ),
    ]
