# Generated by Django 5.0.7 on 2024-07-19 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_history_userhistory_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userhistory',
            options={'verbose_name_plural': "User's History"},
        ),
    ]
