# Generated by Django 5.0.7 on 2024-07-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userhistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='last_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
