# Generated by Django 5.0.7 on 2024-07-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userhistory_last_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
